[package]
name = "mid2text_cli"
version = "1.1.0"
edition = "2024"

[dependencies]
arboard = "3.5.0"
clap = { version = "4.5.36", features = ["derive"] }
mid_text_converter = { path = "../mid_text_converter" }
